package com.niit.dao;

import com.niit.model.Adminuser;

public interface AdminuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminuser
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminuser
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    int insert(Adminuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminuser
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    int insertSelective(Adminuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminuser
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    Adminuser selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminuser
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    int updateByPrimaryKeySelective(Adminuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminuser
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    int updateByPrimaryKey(Adminuser record);
}