package com.niit.dao;

import com.niit.model.Categorysecond;

import java.util.List;

public interface CategorysecondMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorysecond
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    int deleteByPrimaryKey(Integer csid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorysecond
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    int insert(Categorysecond record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorysecond
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    int insertSelective(Categorysecond record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorysecond
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    Categorysecond selectByPrimaryKey(Integer csid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorysecond
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    int updateByPrimaryKeySelective(Categorysecond record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categorysecond
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    int updateByPrimaryKey(Categorysecond record);

    /**
     * 根据一级分类查询二级分类
     * @param cid
     * @return
     */
    List<Categorysecond> getByCategoryId(Integer cid);

}