package com.niit.dao;

import com.niit.model.Product;

import java.util.List;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    Product selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    int updateByPrimaryKey(Product record);

    /**
     * 查询10条热门商品
     * @return
     */
    List<Product> getHotProducts();

    /**
     * 查询10条最新商品
     * @return
     */
    List<Product> getNewProducts();


    /**
     *
     * @Param cid 一级分类id
     * @return
     */
    List<Product> getByCid(Integer cid);


    /**
     *
     * @Param csid 二级分类id
     * @return
     */
    List<Product> getByCsid(Integer csid);
}