package com.niit.model;

public class Adminuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminuser.uid
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminuser.username
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminuser.password
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminuser.uid
     *
     * @return the value of adminuser.uid
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminuser.uid
     *
     * @param uid the value for adminuser.uid
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminuser.username
     *
     * @return the value of adminuser.username
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminuser.username
     *
     * @param username the value for adminuser.username
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminuser.password
     *
     * @return the value of adminuser.password
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminuser.password
     *
     * @param password the value for adminuser.password
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }
}