package com.niit.model;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cid
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cname
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    private String cname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cid
     *
     * @return the value of category.cid
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cid
     *
     * @param cid the value for category.cid
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cname
     *
     * @return the value of category.cname
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cname
     *
     * @param cname the value for category.cname
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    public void setCname(String cname) {
        this.cname = cname;
    }
}