package com.niit.model;

public class Categorysecond {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categorysecond.csid
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    private Integer csid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categorysecond.csname
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    private String csname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categorysecond.cid
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    private Integer cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categorysecond.csid
     *
     * @return the value of categorysecond.csid
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    public Integer getCsid() {
        return csid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categorysecond.csid
     *
     * @param csid the value for categorysecond.csid
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    public void setCsid(Integer csid) {
        this.csid = csid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categorysecond.csname
     *
     * @return the value of categorysecond.csname
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    public String getCsname() {
        return csname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categorysecond.csname
     *
     * @param csname the value for categorysecond.csname
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    public void setCsname(String csname) {
        this.csname = csname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categorysecond.cid
     *
     * @return the value of categorysecond.cid
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categorysecond.cid
     *
     * @param cid the value for categorysecond.cid
     *
     * @mbg.generated Thu Feb 06 09:02:55 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }
}