package com.niit.model;

public class Orderitem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.itemid
     *
     * @mbg.generated Thu Feb 06 09:02:54 CST 2020
     */
    private Integer itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.count
     *
     * @mbg.generated Thu Feb 06 09:02:54 CST 2020
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.subtotal
     *
     * @mbg.generated Thu Feb 06 09:02:54 CST 2020
     */
    private Double subtotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.pid
     *
     * @mbg.generated Thu Feb 06 09:02:54 CST 2020
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.oid
     *
     * @mbg.generated Thu Feb 06 09:02:54 CST 2020
     */
    private Integer oid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.itemid
     *
     * @return the value of orderitem.itemid
     *
     * @mbg.generated Thu Feb 06 09:02:54 CST 2020
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.itemid
     *
     * @param itemid the value for orderitem.itemid
     *
     * @mbg.generated Thu Feb 06 09:02:54 CST 2020
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.count
     *
     * @return the value of orderitem.count
     *
     * @mbg.generated Thu Feb 06 09:02:54 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.count
     *
     * @param count the value for orderitem.count
     *
     * @mbg.generated Thu Feb 06 09:02:54 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.subtotal
     *
     * @return the value of orderitem.subtotal
     *
     * @mbg.generated Thu Feb 06 09:02:54 CST 2020
     */
    public Double getSubtotal() {
        return subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.subtotal
     *
     * @param subtotal the value for orderitem.subtotal
     *
     * @mbg.generated Thu Feb 06 09:02:54 CST 2020
     */
    public void setSubtotal(Double subtotal) {
        this.subtotal = subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.pid
     *
     * @return the value of orderitem.pid
     *
     * @mbg.generated Thu Feb 06 09:02:54 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.pid
     *
     * @param pid the value for orderitem.pid
     *
     * @mbg.generated Thu Feb 06 09:02:54 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.oid
     *
     * @return the value of orderitem.oid
     *
     * @mbg.generated Thu Feb 06 09:02:54 CST 2020
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.oid
     *
     * @param oid the value for orderitem.oid
     *
     * @mbg.generated Thu Feb 06 09:02:54 CST 2020
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }
}